server:
  port: 8080

spring:
  application:
    name: FoundryApplication

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:9090/FoundryERP?useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1422}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        multiTenancy: SCHEMA
        format_sql: true
        show_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public
    locations: classpath:db/migration/public


logging:
  level:
    com.kalibyte.foundry: DEBUG
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  secret: Q0tQeXJmOW9Jb2ZxV2F5cFhUeG5sQzFkQkZpQzZ3c0ZxS0p4cA==
  expiration: 900000
  refresh-expiration: 604800000
