server:
  port: 8080

spring:
  application:
    name: FoundryApplication

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:9090/FondryERP?useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1422}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

jwt:
  secret: change-this-to-256-bit-secret
  expiration-minutes: 120
